apiVersion: v1
kind: Service
metadata:
  name: otel-collector-proxy
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlphttp
  selector:
    app.kubernetes.io/name: opentelemetry-collector