apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bitcoin-api-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: bitcoin-price
  namespaceSelector:
    matchNames:
      - test-bitcoin-price
  endpoints:
    - port: http
      path: /metrics
      interval: 15s