apiVersion: v1
kind: Service
metadata:
  name: test-api-service
  labels:
    app: bitcoin-price
spec:
  type: {{ .Values.service.type }}
  selector:
    app: bitcoin-price
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http